### ISSUE TITLE
ClientID requirement

### ISSUE THREAD

**Issue by ljvmiranda921** [vanishedvan/aseprite-rich-presence#1]
Hi @vanishedvan , thanks for this work! 
It's my first time looking at the Discord RPC API, I'm trying to understand if the Client ID here is something that we still need to generate: https://github.com/vanishedvan/aseprite-rich-presence/blob/master/index.js#L89

Also, if it's a private value, I think we should hide it as an environment variable?

Thanks a lot!

**Comment by ibrahimcaj** [comment]
The Client ID is publicly available anyway, it isn't something that you need to hide. Just create a new application on https://discord.com/developers and copy the Client ID. In this case, you don't need to generate a new ID, because you need this specific one to access the rich presence assets that I made, that are going to be shown on your profile.

Sorry for the late response.
